# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excel_checker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.mycombox import MyComBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 713)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_check = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_check.setGeometry(QtCore.QRect(980, 60, 101, 28))
        self.pushButton_check.setObjectName("pushButton_check")
        self.lineEdit_impt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_impt.setGeometry(QtCore.QRect(120, 20, 841, 21))
        self.lineEdit_impt.setObjectName("lineEdit_impt")
        self.pushButton_impt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_impt.setGeometry(QtCore.QRect(980, 20, 101, 28))
        self.pushButton_impt.setObjectName("pushButton_impt")
        self.textEdit_report = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_report.setGeometry(QtCore.QRect(20, 150, 1061, 511))
        self.textEdit_report.setObjectName("textEdit_report")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label.setObjectName("label")
        self.pushButton_expt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_expt.setGeometry(QtCore.QRect(982, 100, 101, 28))
        self.pushButton_expt.setObjectName("pushButton_expt")
        self.comboBox_empty = MyComBox(self.centralwidget)
        self.comboBox_empty.setGeometry(QtCore.QRect(120, 60, 841, 22))
        self.comboBox_empty.setObjectName("comboBox_empty")
        self.comboBox_repeat = MyComBox(self.centralwidget)
        self.comboBox_repeat.setGeometry(QtCore.QRect(120, 100, 841, 22))
        self.comboBox_repeat.setObjectName("comboBox_repeat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_check.setText(_translate("MainWindow", "校验数据"))
        self.pushButton_impt.setText(_translate("MainWindow", "导入文件"))
        self.label_1.setText(_translate("MainWindow", "校验空值列"))
        self.label_2.setText(_translate("MainWindow", "校验重复值列"))
        self.label.setText(_translate("MainWindow", "待校验文件"))
        self.pushButton_expt.setText(_translate("MainWindow", "保存校验报告"))
