# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handwriting_recognition.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.paintboard import PaintBoard


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.paintboard = PaintBoard(self)
        self.paintboard.setGeometry(QtCore.QRect(20, 20, 400, 400))
        self.paintboard.setObjectName("paintboard")
        self.pushButton_recognize = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_recognize.setGeometry(QtCore.QRect(220, 440, 93, 51))
        self.pushButton_recognize.setObjectName("pushButton_recognize")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(330, 440, 93, 51))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(80, 440, 91, 51))
        self.label_result.setObjectName("label_result")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(20, 450, 31, 31))
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_recognize.setText(_translate("MainWindow", "识别"))
        self.pushButton_clear.setText(_translate("MainWindow", "清空"))
        self.label_result.setText(_translate("MainWindow", "识别结果:"))
